
debug: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accounts_db
    username: root
    password: root1234
  jpa:
    show-sql: true  
    hibernate:
      ddl-auto: create-drop  

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp  

